nelmio_api_doc:
    documentation:
        info:
            title: My API
            description: This is an awesome API!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    
    areas:
        # Área para las rutas de la API que SÍ requieren autenticación
        api:
            path_patterns:
                - '^/api'
            documentation:
                security:
                    - Bearer: []

        # Área para el resto de rutas que NO requieren autenticación
        default:
            path_patterns:
                - '^/((?!(?:_error|_wdt|_profiler|doc)).)*$'